name: Build Aseprite for Windows 10

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'  # Weekly build

env:
  VSWHERE_PATH: 'C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe'
  VSINSTALL_PATH: 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise'

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout Aseprite repository
      uses: actions/checkout@v4
      with:
        repository: aseprite/aseprite
        submodules: recursive
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install Build Dependencies
      run: |
        pip install ninja
        choco install cmake visualstudio2022buildtools
        choco install visualstudio2022-workload-nativedesktop
    
    - name: Setup MSVC
      uses: microsoft/setup-msbuild@v1.1
    
    - name: Configure VS Environment
      run: |
        & "${{ env.VSWHERE_PATH }}" -latest -property installationPath
    
    - name: Clone Skia Dependency
      run: |
        git clone https://github.com/aseprite/skia.git
        cd skia
        python tools/git-sync-deps
    
    - name: Configure Skia
      run: |
        cd skia
        bin/gn gen out/Release-x64 --args="is_official_build=true skia_use_direct3d=true"
        ninja -C out/Release-x64
    
    - name: Configure Aseprite
      run: |
        mkdir build
        cd build
        cmake -G "Visual Studio 17 2022" -A x64 `
          -DCMAKE_BUILD_TYPE=Release `
          -DLAF_BACKEND=windows `
          -DSKIA_DIR=${{ github.workspace }}/skia `
          -DSKIA_LIBRARY_DIR=${{ github.workspace }}/skia/out/Release-x64 `
          ..
    
    - name: Build Aseprite
      run: |
        cd build
        msbuild Aseprite.sln /p:Configuration=Release /m
    
    - name: Package Artifacts
      run: |
        mkdir aseprite-win10
        cp -r build/bin/aseprite.exe aseprite-win10/
        cp -r build/bin/*.dll aseprite-win10/
        cp -r resources aseprite-win10/
        Compress-Archive -Path aseprite-win10 -DestinationPath aseprite-win10-latest.zip
    
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: aseprite-win10
        path: aseprite-win10-latest.zip
        retention-days: 30
