name: Build and deploy Aseprite 

on:
  push:
    branches:
      - master

env:
  BUILD_TYPE: Release
  
jobs:
  build-aseprite:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@v3
      
      - name: Get Skia from cache
        id: skia-cache
        uses: actions/cache@v3
        with:
          path: skia
          key: skia-windows-cache
      
      - name: Download Skia if not in cache
        if: steps.skia-cache.outputs.cache-hit != 'true'
        run: |
          curl -o Skia-Windows-Release-X64.zip -L https://github.com/aseprite/skia/releases/download/m81-b607b32047/Skia-Windows-Release-X64.zip
          unzip Skia-Windows-Release-X64.zip -d skia
      
      - name: Download Aseprite
        run: |
          $latest = (Invoke-RestMethod https://api.github.com/repos/aseprite/aseprite/releases/latest).assets[0].browser_download_url
          Invoke-WebRequest -Uri $latest -OutFile Aseprite-source.zip
          Expand-Archive -Path Aseprite-source.zip -DestinationPath aseprite
          New-Item -Path aseprite/build -ItemType Directory
      
      - name: Build Aseprite
        working-directory: aseprite/build
        run: |
          cmake -DCMAKE_BUILD_TYPE=Release -DLAF_BACKEND=skia -DSKIA_DIR=../../skia -DSKIA_LIBRARY_DIR=../../skia/out/Release-x64 -G Ninja ..
          ninja aseprite
      
      - name: Package Aseprite
        working-directory: aseprite/build/bin
        run: |
          '# Portable config' | Out-File -FilePath aseprite.ini
          7z a Aseprite-win10.zip *
